package uk.co.sentinelweb.cuer.app.ui.common.resources

enum class Icon {
    ic_playlist_close,
    ic_playlist_play,
    ic_playmode_straight,
    ic_button_repeat_24,
    ic_playmode_shuffle,
    ic_person,
    ic_menu_settings_black,
    ic_starred,
    ic_starred_off,

    // platform
    ic_platform_youtube,
    ic_platfrom_web,
    ic_platform_vimeo_24_black,
    ic_platform_podcast,

    // support
    ic_donate,
    ic_coin,
    ic_video,
    ic_social,
    ic_podcast,
    ic_google,
    ic_amazon,
    ic_patreon,
    ic_paypal,
    ic_apple,
    ic_spotify,
    ic_buymeacoffee,
    ic_ko_fi,
    ic_facebook,
    ic_instagram,
    ic_platform_twitter_24_black,
    ic_discord,
    ic_vimeo,
    ic_soundcloud,
    ic_teespring,
    ic_twitch,
    ic_wikipedia,
    ic_tiktok,

    // crypto
    ic_bitcoin,
    ic_eth,
    ic_litecoin,
    ic_doge,
    ic_xmr,
    ic_ripple,
    ic_neo,
    ic_dash,
    ic_bitcoincash,
    ic_algo,
    ic_cardano,
}