name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode google-services file
        run: echo $GS > ./app/google-services.json
        env:
          GS: "${{ secrets.GOOGLESERVICES_JSON }}"
      - name: Build
        run: ./gradlew -PCUER_YOUTUBE_API_KEY=$YT_KEY build
        env:
          YT_KEY: "${{ secrets.CUER_YOUTUBE_API_KEY }}"
      - name: Test
        run: ./gradlew -PCUER_YOUTUBE_API_KEY=$YT_KEY core:test domain:test net:test app:testDebugUnitTest
        env:
          YT_KEY: "${{ secrets.CUER_YOUTUBE_API_KEY }}"
