name: Android CI

on:
  push:
    branches: [ develop ]
  #    paths:
  #      - app/**
  #      - remote/**
  #      - shared/**
  #      - net/**
  pull_request:
    branches:
      - feature/**
      - bugfix/**
      - develop
      - main
#    paths:
#      - app/**
#      - remote/**
#      - shared/**
#      - net/**
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode google-services file
        run: echo $GS > ./app/google-services.json
        env:
          GS: "${{ secrets.GOOGLESERVICES_JSON }}"
      - name: Build
        run: ./gradlew -PCUER_YOUTUBE_API_KEY=CUER_YOUTUBE_API_KEY -PCUER_PIXABAY_API_KEY=CUER_PIXABAY_API_KEY -PCUER_SIGNING_KEY_ALIAS=$CUER_SIGNING_KEY_ALIAS -PCUER_SIGNING_KEY_FILE=$CUER_SIGNING_KEY_FILE -PCUER_SIGNING_PASSWORD=$CUER_SIGNING_PASSWORD -PCUER_UPLOAD_KEY_ALIAS=$CUER_UPLOAD_KEY_ALIAS -PCUER_UPLOAD_KEY_FILE=$CUER_UPLOAD_KEY_FILE -PCUER_UPLOAD_PASSWORD=$CUER_UPLOAD_PASSWORD -PCUER_HUB_STORE_KEY=CUER_HUB_STORE_KEY -PCUER_HUB_STORE_PASS=CUER_HUB_STORE_PASS clean :app:assembleDebug linkPodDebugFrameworkIosX64 :hub:generateApiKeyClass :hub:generateApiKeyClass :hub:build
        env:
          CUER_YOUTUBE_API_KEY: "${{ secrets.CUER_YOUTUBE_API_KEY }}"
          CUER_PIXABAY_API_KEY: "${{ secrets.CUER_PIXABAY_API_KEY }}"
          CUER_SIGNING_KEY_ALIAS: "${{ secrets.CUER_SIGNING_KEY_ALIAS }}"
          CUER_SIGNING_KEY_FILE: "${{ secrets.CUER_SIGNING_KEY_FILE }}"
          CUER_SIGNING_PASSWORD: "${{ secrets.CUER_SIGNING_PASSWORD }}"
          CUER_UPLOAD_KEY_ALIAS: "${{ secrets.CUER_UPLOAD_KEY_ALIAS }}"
          CUER_UPLOAD_KEY_FILE: "${{ secrets.CUER_UPLOAD_KEY_FILE }}"
          CUER_UPLOAD_PASSWORD: "${{ secrets.CUER_UPLOAD_PASSWORD }}"
          CUER_HUB_STORE_KEY: "${{ secrets.CUER_HUB_STORE_KEY }}"
          CUER_HUB_STORE_PASS: "${{ secrets.CUER_HUB_STORE_PASS }}"
      - name: Test
        run: ./gradlew -PCUER_YOUTUBE_API_KEY=CUER_YOUTUBE_API_KEY -PCUER_PIXABAY_API_KEY=CUER_PIXABAY_API_KEY -PCUER_SIGNING_KEY_ALIAS=$CUER_SIGNING_KEY_ALIAS -PCUER_SIGNING_KEY_FILE=$CUER_SIGNING_KEY_FILE -PCUER_SIGNING_PASSWORD=$CUER_SIGNING_PASSWORD -PCUER_UPLOAD_KEY_ALIAS=$CUER_UPLOAD_KEY_ALIAS -PCUER_UPLOAD_KEY_FILE=$CUER_UPLOAD_KEY_FILE -PCUER_UPLOAD_PASSWORD=$CUER_UPLOAD_PASSWORD -PCUER_HUB_STORE_KEY=CUER_HUB_STORE_KEY -CUER_HUB_STORE_PASS=CUER_HUB_STORE_PASS database:verifyCommonMainDatabaseMigration shared:test shared:jvmTest net:test domain:test database:test app:testDebugUnitTest :hub:test
        # https://issuetracker.google.com/issues/192927707
        #        app:testDebugUnitTest
        env:
          CUER_YOUTUBE_API_KEY: "${{ secrets.CUER_YOUTUBE_API_KEY }}"
          CUER_PIXABAY_API_KEY: "${{ secrets.CUER_PIXABAY_API_KEY }}"
          CUER_SIGNING_KEY_ALIAS: "${{ secrets.CUER_SIGNING_KEY_ALIAS }}"
          CUER_SIGNING_KEY_FILE: "${{ secrets.CUER_SIGNING_KEY_FILE }}"
          CUER_SIGNING_PASSWORD: "${{ secrets.CUER_SIGNING_PASSWORD }}"
          CUER_UPLOAD_KEY_ALIAS: "${{ secrets.CUER_UPLOAD_KEY_ALIAS }}"
          CUER_UPLOAD_KEY_FILE: "${{ secrets.CUER_UPLOAD_KEY_FILE }}"
          CUER_UPLOAD_PASSWORD: "${{ secrets.CUER_UPLOAD_PASSWORD }}"
          CUER_HUB_STORE_KEY: "${{ secrets.CUER_HUB_STORE_KEY }}"
          CUER_HUB_STORE_PASS: "${{ secrets.CUER_HUB_STORE_PASS }}"
