name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - feature/**
      - bugfix/**
      - develop
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      #      - uses: actions/setup-node@v1
      #        with:
      #          node-version: 14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode google-services file
        run: echo $GS > ./app/google-services.json
        env:
          GS: "${{ secrets.GOOGLESERVICES_JSON }}"
      - name: Build
        run: ./gradlew -PCUER_YOUTUBE_API_KEY=$YT_KEY -PCUER_PIXABAY_API_KEY=$PIXABAY_KEY clean assembleDebug
        env:
          YT_KEY: "${{ secrets.CUER_YOUTUBE_API_KEY }}"
          PIXABAY_KEY: "${{ secrets.CUER_PIXABAY_API_KEY }}"
      - name: Test
        run: ./gradlew -PCUER_YOUTUBE_API_KEY=$YT_KEY -PCUER_PIXABAY_API_KEY=$PIXABAY_KEY core:test shared:test net:test app:testDebugUnitTest
        env:
          YT_KEY: "${{ secrets.CUER_YOUTUBE_API_KEY }}"
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
